name: google_sign_in_web_integration_tests
publish_to: none

environment:
  sdk: ^3.3.0
  flutter: ">=3.19.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  google_identity_services_web: ^0.3.3
  google_sign_in_platform_interface: 
    git: https://github.com/kumsumit/google_sign_in_platform_interface.git
  google_sign_in_web:
    path: ../

dev_dependencies:
  build_runner: ^2.1.1
  flutter_test:
    sdk: flutter
  http: ">=0.13.0 <2.0.0"
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  web: ^1.0.0

dependencies_overrides:
  google_sign_in_platform_interface:  
    git: https://github.com/kumsumit/google_sign_in_platform_interface.git

flutter:
  uses-material-design: true
